#!/bin/sh

# Xcode Cloud post-clone step.
# The Xcode project is generated by XcodeGen and is not committed to git
# (see .gitignore). Install XcodeGen and generate Sunday.xcodeproj so the
# cloud runner has a project to build.

set -e

echo "Installing XcodeGen…"
brew install xcodegen

echo "Generating Xcode project from project.yml…"
cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate

echo "XcodeGen finished. Contents of repository root:"
ls -la "$CI_PRIMARY_REPOSITORY_PATH" | grep -i xcodeproj
